#!/usr/bin/env bash

set -e

decompress_file() {
	local folder="/usr/share/fonts/truetype"
	local file="$folder/msttcorefonts-extra.tar.zst"

	echo -e "\nDecompressing font files...\n"
	tar --zstd -xvf "$file" -C "$folder" && rm -f "$file"
}

decompress_file
